### PR TITLE
add new srv ApplyPlanningScene

### PR DESCRIPTION
**Pull request by v4hn**
This service takes a PlanningScene message and applies it to the monitored
scene.

See https://groups.google.com/forum/#!topic/moveit-users/D7MWZEUSKLc
for a discussion on why this makes sense to add.

Ideally it should include a `bool success` field, but it is not possible to
apply the scene and check for success without ABI changes, so leave it out for
now to get this change pushed to indigo.

With kinetic we might want to think about adding a `bool success` field here
and make ```newPlanningSceneMessage``` return ```bool``` instead of ```void```.

### CODE REVIEW

**Comment by davetcoleman** [comment]
why not go ahead and add the ``success`` field to the message and we can connect it to something other than true in the future?

i hope you'll make  ``newPlanningSceneMessage()`` return true in jade/kinetic

**Comment by v4hn** [comment]
I thought it's probably confusing to have a constantly true
```success``` field in the action, but you're probably right.
There's no need to change the action spec later on.

I adjusted the spec accordingly.

**Comment by davetcoleman** [comment]
@mikeferguson you're our ROS messages expert, think its ok to go ahead and merge this now or do I need to wait for something?

**Comment by mikeferguson** [comment]
@davetcoleman -- it is an entirely new message, right? That is pretty much always fine, it is just changing messages that is problematic.

**Pull request merged**
