### PR TITLE
Change action name path -> trajectory for better name

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/ros-planning/moveit_msgs/pull/24#issuecomment-241102064

### CODE REVIEW

**Comment by rhaschke** [comment]
Thanks @wkentaro. Cherry-picked to Jade.

**Comment by rhaschke** [comment]
I suggest, to drop this new feature (of TrajectoryExecution action) for `Indigo` for the following reason:
The MoveGroupInterface tries to connect to the new action for trajectory execution. However, as existing moveit configs don't define this new capability yet, we need to issue a deprecation warning. However, this shouldn't happen for an LTS release like Indigo. I suggest to deprecate beginning with `Jade`. The new feature is functionally not required.
@davetcoleman @v4hn: What do you think?

**Comment by v4hn** [comment]
@rhaschke Could you have a look at the solution I proposed in https://github.com/ros-planning/moveit/issues/38 . Maybe something similar works for this patch? (we could even silently support the action in indigo to enable users to use the same code from indigo to kinetic).
Note though, that the change there is a medium safety issue and *should* be addressed in indigo.

If the new action is not functionally required in indigo to allow for proper cancelling of trajectories,
then yes, it would be ok to have it only starting in jade.

**Comment by rhaschke** [comment]
@v4hn That's exactly, what I implemented. However, I think we shouldn't bother people with a deprecation warning in the middle of the lifetime of Indigo, should we?

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/12423 I made a release request for indigo that includes this patch but closed it before it's accepted, waiting for the discussion to be settled here.

**Comment by v4hn** [comment]
On Sat, Aug 20, 2016 at 08:11:06AM -0700, Robert Haschke wrote:
> @v4hn That's exactly, what I implemented. However, I think we shouldn't bother people with a deprecation warning in the middle of the lifetime of Indigo, should we?

So why not silently fall back to the current version if the new one is not available?
We could add the deprecation warning starting with jade.
This would allow to use the feature in indigo but wouldn't bother anyone.

**Comment by rhaschke** [comment]
> So why not silently fall back to the current version if the new one is not available?

That would be an option.

> We could add the deprecation warning starting with jade.

+1 That's what I suggested.

> This would allow to use the feature in indigo but wouldn't bother anyone.

Agreed.

**Comment by davetcoleman** [comment]
+1

**Comment by v4hn** [comment]
So this looks like having the action spec released in indigo-devel is fine.
@130s I believe the discussion "is settled" :)

**Comment by 130s** [comment]
Aye.

(I'll actually have to make a new release for IJK, instead of re-opening https://github.com/ros/rosdistro/pull/12423, to include https://github.com/ros-planning/moveit_msgs/pull/28)

**Comment by 130s** [comment]
New release request for 0.7.4 for Indigo https://github.com/ros/rosdistro/pull/12451

**Pull request merged**
