### PR TITLE
Bump version to 0.11.1

### PR DESCRIPTION
**Pull request by tylerjw**

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]

**Comment by tylerjw** [comment]
@rhaschke I don't know if you can push a tag with a PR but I tagged this locally and intended to just push this onto master, but the protected branch feature of github prevented me.

**Comment by tylerjw** [comment]
Do you know how to push a tag onto a protected branch?

**Comment by rhaschke** [comment]
@tylerjw, IMO you don't need to create PRs for auto-generated changes like version bumps. I hope you can push them directly as well as a maintainer, can't you?

**Comment by tylerjw** [comment]
No, github wouldn't let me because `master` is a protected branch.

**Comment by tylerjw** [comment]
```bash
$ git push origin_ssh master 
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 332 bytes | 332.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Travis CI - Pull Request" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:ros-planning/moveit_msgs.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:ros-planning/moveit_msgs.git'
```

**Comment by tylerjw** [comment]
never mind, i can push a tag, just not a commit

**Comment by rhaschke** [comment]
Ok. Maybe, I should perform the final `catkin_prepare_release` step then?
We should discuss that issue in the next maintainer meeting. The branch protection is important, I think, but extremely slows down the release process.
I just pushed the 0.11.1 tag. So, you should be able to proceed with bloom.

**Comment by tylerjw** [comment]
@rhaschke I can push a tag... found it in the docs, just not commits.  That's fine I guess.

**Pull request merged**
