### PR TITLE
[melodic-devel] Jog arm backport

### PR DESCRIPTION
**Pull request by tylerjw**
Backporting these PRs to melodic-devel for jog arm:
* https://github.com/ros-planning/moveit_msgs/pull/68
* https://github.com/ros-planning/moveit_msgs/pull/63

@AndyZe please review and let me know if this is all that will be needed to before we can add jog arm to melodic_devel in moveit.

### CODE REVIEW

**Comment by AndyZe** [comment]
@tylerjw  PR #1724 would have needed these changes. It still hasn't been merged into MoveIt, so this PR is not necessary to backport jog_arm.

The message type that we do need is this one:
https://github.com/ros-planning/moveit_msgs/pull/63

Thanks for the effort/ let me know if you are very busy and I should make the PR instead.

**Comment by tylerjw** [comment]
@AndyZe I added #63 to this.

**Comment by AndyZe** [comment]
Looks good to me!

**Comment by mlautman** [comment]
@v4hn might have an opinion regarding cherry-picking vs making this PR a separate thing

**Comment by tylerjw** [comment]
@v4hn ping on this.  Is there something different I should have done with the commits for this?

**Comment by v4hn** [comment]
I guess you cherry-picked the commits, right? That's exactly what I would have done too.

The only thing you should keep in mind is that once we release the `melodic-devel` branch again, we should not change the messages there ever again.
So if you consider other message changes for jog-arm in the near future, you might want to include them soon.
That aside, any maintainer involved with these new messages might merge (preferably as individual commits or via a merge commit to keep the cherry-picks in the history).

**Comment by tylerjw** [comment]
@AndyZe any other changes to moveit_msgs you expect we should add for jog_arm?

**Pull request merged**
