### PR TITLE
Removed identical services per issue #4 and unused service from issue #4

### PR DESCRIPTION
**Pull request by davetcoleman**
Addresses @isucan's old issues:
https://github.com/ros-planning/moveit_msgs/issues/3
https://github.com/ros-planning/moveit_msgs/issues/4

### CODE REVIEW

**Comment by davetcoleman** [comment]
Requires https://github.com/ros-planning/moveit/pull/361 to pass

**Comment by 130s** [comment]
Let me understand where you're suggesting:
- Apply the change in this PR only to Kinetic.
- First release from each distro branch with the current status, then this PR should pass?

I'm working on the release #33 but just wonder if we want this change to be included into the kinetic release right away or not.

**Comment by davetcoleman** [comment]
I think it would be best to release moveit_msgs before this PR -

- to allow time for debating this change without holding up the forever-late kinetic release
- to not break developers who build moveit from source but used moveit_msgs from debian and don't sync to ``kinetic-devel`` very often

**Comment by 130s** [comment]
> I think it would be best to release moveit_msgs before this PR -

Done https://github.com/ros/rosdistro/pull/13221, and the Travis passes now for this PR.
Now that `moveit` is release requested https://github.com/ros/rosdistro/pull/13230 (3rd time) and hopefully it won't cause any buildfarm issue this time, which means we're about to be ready to say that MoveIt! is finally released into Kinetic, I guess we should make a release of `moveit_msgs` with the change in this PR before making announcement (if so I will do so)?

**Comment by davetcoleman** [comment]
I think we should hold off on releasing this until next time we release all of moveit - hopefully in a month or two - for the reason: "to not break developers who build moveit from source but used moveit_msgs from debian and don't sync to kinetic-devel very often"

**Comment by 130s** [comment]
Prerelease test passed for Wily and Xenial, and release requested into Kinetic https://github.com/ros/rosdistro/pull/13802 as I'm making a release of MoveIt! as well https://github.com/ros-planning/moveit/issues/393

**Pull request merged**
